# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_movies.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_movies_dialog(object):
    def setupUi(self, add_movies_dialog):
        add_movies_dialog.setObjectName("add_movies_dialog")
        add_movies_dialog.resize(808, 456)
        self.verticalLayout = QtWidgets.QVBoxLayout(add_movies_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.category_tabs = QtWidgets.QTabWidget(add_movies_dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.category_tabs.setFont(font)
        self.category_tabs.setFocusPolicy(QtCore.Qt.NoFocus)
        self.category_tabs.setObjectName("category_tabs")
        self.p_inc_tab = QtWidgets.QWidget()
        self.p_inc_tab.setObjectName("p_inc_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.p_inc_tab)
        self.gridLayout.setObjectName("gridLayout")
        self.p_inc_list_widget = QtWidgets.QListWidget(self.p_inc_tab)
        self.p_inc_list_widget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.p_inc_list_widget.setObjectName("p_inc_list_widget")
        self.gridLayout.addWidget(self.p_inc_list_widget, 0, 0, 1, 1)
        self.category_tabs.addTab(self.p_inc_tab, "")
        self.y_ish_tab = QtWidgets.QWidget()
        self.y_ish_tab.setObjectName("y_ish_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.y_ish_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.y_ish_list_widget = QtWidgets.QListWidget(self.y_ish_tab)
        self.y_ish_list_widget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.y_ish_list_widget.setObjectName("y_ish_list_widget")
        self.gridLayout_2.addWidget(self.y_ish_list_widget, 0, 0, 1, 1)
        self.category_tabs.addTab(self.y_ish_tab, "")
        self.t_ish_tab = QtWidgets.QWidget()
        self.t_ish_tab.setObjectName("t_ish_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.t_ish_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.t_ish_list_widget = QtWidgets.QListWidget(self.t_ish_tab)
        self.t_ish_list_widget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.t_ish_list_widget.setObjectName("t_ish_list_widget")
        self.gridLayout_3.addWidget(self.t_ish_list_widget, 0, 0, 1, 1)
        self.category_tabs.addTab(self.t_ish_tab, "")
        self.s_inc_tab = QtWidgets.QWidget()
        self.s_inc_tab.setObjectName("s_inc_tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.s_inc_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.s_inc_list_widget = QtWidgets.QListWidget(self.s_inc_tab)
        self.s_inc_list_widget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.s_inc_list_widget.setObjectName("s_inc_list_widget")
        self.gridLayout_4.addWidget(self.s_inc_list_widget, 0, 0, 1, 1)
        self.category_tabs.addTab(self.s_inc_tab, "")
        self.d_ish_tab = QtWidgets.QWidget()
        self.d_ish_tab.setObjectName("d_ish_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.d_ish_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.d_ish_list_widget = QtWidgets.QListWidget(self.d_ish_tab)
        self.d_ish_list_widget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.d_ish_list_widget.setObjectName("d_ish_list_widget")
        self.gridLayout_5.addWidget(self.d_ish_list_widget, 0, 0, 1, 1)
        self.category_tabs.addTab(self.d_ish_tab, "")
        self.verticalLayout.addWidget(self.category_tabs)
        self.buttonBox = QtWidgets.QDialogButtonBox(add_movies_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(add_movies_dialog)
        self.category_tabs.setCurrentIndex(0)
        self.buttonBox.accepted.connect(add_movies_dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(add_movies_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(add_movies_dialog)

    def retranslateUi(self, add_movies_dialog):
        _translate = QtCore.QCoreApplication.translate
        add_movies_dialog.setWindowTitle(_translate("add_movies_dialog", "Add Movies"))
        self.p_inc_tab.setToolTip(_translate("add_movies_dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Possible movies to add to the AMDb database</span></p><p><br/></p><p>These movie files appear to include a valid title and year. There is a high likelihood that these movies will be found online. It is recommended that you select all the movies in this list.</p></body></html>"))
        self.category_tabs.setTabText(self.category_tabs.indexOf(self.p_inc_tab), _translate("add_movies_dialog", "Possible Inclusions"))
        self.y_ish_tab.setToolTip(_translate("add_movies_dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Some issues extracting release year</span></p><p><br/></p><p>These movies have some potential issues, it appears the year couldn\'t be extracted. Review the list carefully before selecting any movies from this list as there is a chance the movie will not be found online.<br/>The release year is not required however it is highly recomended to include the year in the online search.</p></body></html>"))
        self.category_tabs.setTabText(self.category_tabs.indexOf(self.y_ish_tab), _translate("add_movies_dialog", "Year Issues"))
        self.t_ish_tab.setToolTip(_translate("add_movies_dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Some issues with movie title</span></p><p><br/></p><p>These files have been detected as movie files, however the movie title appears to be unrelated to its containing folder, and no valid year could be determined.</p><p>Movies selected from this list might fail when searching for data on the internet.</p></body></html>"))
        self.category_tabs.setTabText(self.category_tabs.indexOf(self.t_ish_tab), _translate("add_movies_dialog", "Title Issues"))
        self.category_tabs.setTabText(self.category_tabs.indexOf(self.s_inc_tab), _translate("add_movies_dialog", "Series Files"))
        self.d_ish_tab.setToolTip(_translate("add_movies_dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Movies have a current AMDb database entry</span></p><p><br/></p><p>Movies in this list are duplicates, meaning the file already has an entry in the database. Movies selected from this list will overwrite the current entry if data is found online. Review the list carefully and decide if you want to risk overwriting any movie data.</p><p>It is not generally advised to select movies from this list.</p></body></html>"))
        self.category_tabs.setTabText(self.category_tabs.indexOf(self.d_ish_tab), _translate("add_movies_dialog", "Duplicates"))
