# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'keywords_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 280)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.new_keyword = QtWidgets.QLineEdit(Form)
        self.new_keyword.setMinimumSize(QtCore.QSize(0, 23))
        self.new_keyword.setMaximumSize(QtCore.QSize(16777215, 23))
        self.new_keyword.setObjectName("new_keyword")
        self.gridLayout.addWidget(self.new_keyword, 1, 0, 1, 1)
        self.movie_title = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.movie_title.setFont(font)
        self.movie_title.setWordWrap(True)
        self.movie_title.setObjectName("movie_title")
        self.gridLayout.addWidget(self.movie_title, 0, 0, 1, 2)
        self.keyword_list = QtWidgets.QListWidget(Form)
        self.keyword_list.setObjectName("keyword_list")
        self.gridLayout.addWidget(self.keyword_list, 2, 0, 1, 2)
        self.add_keyword = QtWidgets.QPushButton(Form)
        self.add_keyword.setMinimumSize(QtCore.QSize(0, 23))
        self.add_keyword.setMaximumSize(QtCore.QSize(16777215, 23))
        self.add_keyword.setObjectName("add_keyword")
        self.gridLayout.addWidget(self.add_keyword, 1, 1, 1, 1)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancel_button = QtWidgets.QPushButton(self.frame)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.save_button = QtWidgets.QPushButton(self.frame)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout.addWidget(self.save_button)
        self.gridLayout.addWidget(self.frame, 3, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.add_keyword.setText(_translate("Form", "Add Keyword"))
        self.cancel_button.setText(_translate("Form", "Cancel"))
        self.save_button.setText(_translate("Form", "Save Changes"))
