# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'movie_grid.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_movie_grid(object):
    def setupUi(self, movie_grid):
        movie_grid.setObjectName("movie_grid")
        movie_grid.resize(310, 540)
        self.verticalLayout = QtWidgets.QVBoxLayout(movie_grid)
        self.verticalLayout.setContentsMargins(5, 20, 5, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.movie_title = QtWidgets.QLabel(movie_grid)
        self.movie_title.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.movie_title.setFont(font)
        self.movie_title.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.movie_title.setObjectName("movie_title")
        self.verticalLayout.addWidget(self.movie_title)
        self.movie_poster = QtWidgets.QLabel(movie_grid)
        self.movie_poster.setMinimumSize(QtCore.QSize(300, 420))
        self.movie_poster.setMaximumSize(QtCore.QSize(300, 450))
        self.movie_poster.setScaledContents(True)
        self.movie_poster.setObjectName("movie_poster")
        self.verticalLayout.addWidget(self.movie_poster)
        self.movie_genre = QtWidgets.QLabel(movie_grid)
        self.movie_genre.setMaximumSize(QtCore.QSize(16777215, 12))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.movie_genre.setFont(font)
        self.movie_genre.setAlignment(QtCore.Qt.AlignCenter)
        self.movie_genre.setObjectName("movie_genre")
        self.verticalLayout.addWidget(self.movie_genre)

        self.retranslateUi(movie_grid)
        QtCore.QMetaObject.connectSlotsByName(movie_grid)

    def retranslateUi(self, movie_grid):
        pass
