# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(345, 300)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tt_edit = QtWidgets.QLineEdit(self.frame)
        self.tt_edit.setMaximumSize(QtCore.QSize(16777215, 22))
        self.tt_edit.setMaxLength(12)
        self.tt_edit.setObjectName("tt_edit")
        self.horizontalLayout.addWidget(self.tt_edit)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setMaximumSize(QtCore.QSize(26, 22))
        self.pushButton.setText("")
        icon = QtGui.QIcon.fromTheme("go-jump")
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(14, 14))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.frame)
        self.movie_list_widget = QtWidgets.QListWidget(Dialog)
        self.movie_list_widget.setObjectName("movie_list_widget")
        self.verticalLayout.addWidget(self.movie_list_widget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.poster_preview = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.poster_preview.sizePolicy().hasHeightForWidth())
        self.poster_preview.setSizePolicy(sizePolicy)
        self.poster_preview.setMinimumSize(QtCore.QSize(150, 226))
        self.poster_preview.setMaximumSize(QtCore.QSize(300, 455))
        self.poster_preview.setPixmap(QtGui.QPixmap("../../../AMDb4/2fb5d26e/tt_0000000.png"))
        self.poster_preview.setScaledContents(True)
        self.poster_preview.setObjectName("poster_preview")
        self.horizontalLayout_2.addWidget(self.poster_preview)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Select Movie"))
        self.tt_edit.setPlaceholderText(_translate("Dialog", "tt01234321"))
