# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_log.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LogViewer(object):
    def setupUi(self, LogViewer):
        LogViewer.setObjectName("LogViewer")
        LogViewer.resize(633, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(LogViewer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logs_table = QtWidgets.QTableWidget(LogViewer)
        self.logs_table.setShowGrid(False)
        self.logs_table.setObjectName("logs_table")
        self.logs_table.setColumnCount(3)
        self.logs_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.logs_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.logs_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.logs_table.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.logs_table)

        self.retranslateUi(LogViewer)
        QtCore.QMetaObject.connectSlotsByName(LogViewer)

    def retranslateUi(self, LogViewer):
        _translate = QtCore.QCoreApplication.translate
        LogViewer.setWindowTitle(_translate("LogViewer", "AMDb Logs"))
        self.logs_table.setSortingEnabled(True)
        item = self.logs_table.horizontalHeaderItem(0)
        item.setText(_translate("LogViewer", "Date"))
        item = self.logs_table.horizontalHeaderItem(1)
        item.setText(_translate("LogViewer", "Log Type"))
        item = self.logs_table.horizontalHeaderItem(2)
        item.setText(_translate("LogViewer", "Message"))
